theme = "no_background"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false
git-exclude = false

[keys.normal]
"A-s" = ":w"

[keys.insert]
"A-s" = ":w"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.soft-wrap]
enable = true

# just for master branch, not yet on release helix
# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"
